contact_links:
  - name: ðŸ“š Documentation
    url: https://nuxt.com/docs/
    about: Check documentation for usage
  - name: ðŸ’¬ Discussions
    url: https://github.com/nuxt/bridge/discussions
    about: Use discussions if you have an idea for improvement and asking questions
